# Generated by Django 3.2.9 on 2021-11-23 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='working_group',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='working_group'),
        ),
    ]
